version: 2
updates:
  # Enable updates for pub (Flutter/Dart) packages
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "john"
    labels:
      - "dependencies"
      - "automerge"

  # Enable updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "john"
    labels:
      - "dependencies"
      - "automerge"
