name: Configure Secrets

on:
  workflow_call:
    secrets:
      KEYSTORE_FILE_BASE64:
        required: false
      KEYSTORE_PASSWORD:
        required: false
      KEY_ALIAS:
        required: false
      KEY_PASSWORD:
        required: false

jobs:
  decode-secrets:
    runs-on: ubuntu-latest
    if: ${{ inputs.KEYSTORE_FILE_BASE64 != '' }}
    steps:
      - name: Decode Android keystore
        if: ${{ secrets.KEYSTORE_FILE_BASE64 != '' }}
        run: |
          mkdir -p android/app/keystore
          echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 --decode > android/app/keystore/release.jks
          echo "KEYSTORE_FILE=android/app/keystore/release.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
    outputs:
      keystore-set: ${{ steps.check-secrets.outputs.keystore-set }}
